# directory for all generated output
OUTDIR: "SuRE-pipelineOutput"
# expected adapter sequence in cDNA reads
ADPT_SEQ: "CCTAGCTAACTATAACGGTCCTAAGGTAGCGAA"
# expected adapter sequence in forward iPCR reads
ADPTR_IPCR_FORW_SEQ: "CCTAGCTAACTATAACGGTCCTAAGGTAGCGAACCAGTGAT"
# expected adapter sequence in reverse iPCR reads
ADPTR_IPCR_REV_SEQ: "CCAGTCGT"

# early SuRE experiemts included a step for shortening iPCR selfligated
# circles. This was done by cutting a restriction site in the gDNA of ligated
# circle, followed by religation (I think). This section defines different such
# restriction motifs. Nowadays the fragments generatedd are shorter so that
# this step is no longer required.
CUTMOTIF_CATG: &CUTMOTIF_CATG 
  "CATG"
CUTMOTIF_TCGA: &CUTMOTIF_TGCA 
  "TGCA"
CUTMOTIF_NONE: &CUTMOTIF_NONE
  ""

# This section defines the genotypes of 5 specific libraries. These settings
# allow selection of specific SNP sets for annotating the data.
SuRE42_GID: &SURE42_GID
  "HG02601"
SuRE43_GID: &SURE43_GID
  "NA18983"
SuRE44_GID: &SURE44_GID
  "HG01241"
SuRE45_GID: &SURE45_GID
  "HG03464"
# genotype selection for a particular dataset
GID: *SURE45_GID

# location of reference sequence index file for bowtie2
BOWTIE2_REFSEQ: "$HOME/data/bowtie2-indexes/hg19_ch1-22_XYM"
# a bowtie2 setting which specifies the maximum length of the fragments. This
# setting strongly affects the running time of the bowtie2 step. Current
# setting is probably somewhat higher than necessary.
MAX_INSERT_LENGTH: 1000
# number of cores. This is generally overridden by the commandline argument '--cores'
NCORES: 30
# genome assembly (not sure why/where this is used :-( )
ASSEMBLY: "hg19"
# specify which chromosomes will be included in the data processing
# use this to run the pipeline on a limited (test) data set
CHR_TARGET:
  - chr1
  - chr2
  - chr3
  - chr21
  - chr22
  - chrX
  - chrY
# select the processing to include SNPs or not
# ALLELE_SPECIFIC: "yes"
ALLELE_SPECIFIC: 0
# if ALLELE_SPECIFIC this folder will contain the SNP annotation (what format?)
SNP_DIR: "/DATA/home/ludo/projects/LP140430_SureSeq_JvArensbergen/data/LP170210_SuRE42-45_1000Genomes/"

###################################################
# The above settings are 'general' ################
# Below are settings to specify input data files ##
###################################################

# section for specifying cDNA 
cDNA:
  # location of folder with cDNA fastq files
  FASTQ_DIR:
    "/home/NFS/users/l.pagie/projects/LP140430_SureSeq_JvArensbergen/analyses/LP161219_SuRE23_reProc/fastq/cDNA/"
  # name of folder in 'OUTDIR' for cDNA related output
  OUTDIR:
    "cDNA"
  # name of samples (used to label data files and data columns) with a list of fastq filenames
  SAMPLES:
    SuRE23_45_B1_T1:
      - 3520_1_12_1_RNA_45_5_K562_SuRE23_TFrep1_PCRrep1_pgcDNA_adapter_2_150604_hg_CAGATCA_L002_R1_001.fastq.gz
    SuRE23_45_B1_T2:
      - 3520_2_12_2_RNA_45_5_K562_SuRE23_TFrep1_PCRrep2_pgcDNA_adapter_2_150604_hg_ACTTGAA_L002_R1_001.fastq.gz
    SuRE23_45_B1_T3:
      - 3520_3_12_3_RNA_45_6_K562_SuRE23_TFrep2_PCRrep1_pgcDNA_adapter_2_150604_hg_GATCAGA_L002_R1_001.fastq.gz
    SuRE23_45_B1_T4:
      - 3520_4_12_4_RNA_45_6_K562_SuRE23_TFrep2_PCRrep2_pgcDNA_adapter_2_150604_hg_TAGCTTA_L002_R1_001.fastq.gz
    SuRE23_55_B2_T1:
      - 3875_1_16_1_RNA_55_5_K562_SuRE23_PCRrep1_ATCACGA_S63_L008_R1_001.fastq.gz
    SuRE23_55_B2_T2:
      - 3875_2_16_2_RNA_55_5_K562_SuRE23_PCRrep2_CGATGTA_S64_L008_R1_001.fastq.gz

plDNA:
  FASTQ_DIR:
    "/home/NFS/users/l.pagie/projects/LP140430_SureSeq_JvArensbergen/analyses/LP161219_SuRE23_reProc/fastq/plDNA/"
  OUTDIR:
    "plDNA"
  SAMPLES:
    plDNA.1:
      - 3419_29_10_29_Sce1_plDNA_SuRE23_PCRrep1_TACCTTA_L002_R1_001.fastq.gz
    plDNA.2:
      - 3419_30_10_30_Sce1_plDNA_SuRE23_PCRrep2_CTGTGTA_L002_R1_001.fastq.gz

iPCR:
  FASTQ_DIR:
    "/home/NFS/users/l.pagie/projects/LP140430_SureSeq_JvArensbergen/analyses/LP161219_SuRE23_reProc/fastq/iPCR/"
  OUTDIR:
    "iPCR"
  SAMPLES:
    iPCR_3262_2:
    # named list specifying fastq files forward and reverse reads respectively, 
    # and the restriction motif used to make iPCR ligated circles smaller
      R1: 3262_2_SuRE23_iPCR_1_CGATGTA_L001_R1_001.fastq.gz
      R2: 3262_2_SuRE23_iPCR_1_CGATGTA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3262_3: 
      R1: 3262_3_SuRE23_iPCR_2_TTAGGCA_L001_R1_001.fastq.gz
      R2: 3262_3_SuRE23_iPCR_2_TTAGGCA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3262_4: 
      R1: 3262_4_SuRE23_iPCR_3_TGACCAA_L001_R1_001.fastq.gz
      R2: 3262_4_SuRE23_iPCR_3_TGACCAA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3262_5: 
      R1: 3262_5_SuRE23_iPCR_4_ACAGTGA_L001_R1_001.fastq.gz
      R2: 3262_5_SuRE23_iPCR_4_ACAGTGA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3262_6: 
      R1: 3262_6_SuRE23_iPCR_5_GCCAATA_L001_R1_001.fastq.gz
      R2: 3262_6_SuRE23_iPCR_5_GCCAATA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3336_1: 
      R1: 3336_1_150122_SuRE23_iPCR_1_CGATGTA_R1_001.fastq.gz
      R2: 3336_1_150122_SuRE23_iPCR_1_CGATGTA_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3336_2: 
      R1: 3336_2_150122_SuRE23_iPCR_2_TTAGGCA_R1_001.fastq.gz
      R2: 3336_2_150122_SuRE23_iPCR_2_TTAGGCA_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3336_3: 
      R1: 3336_3_150122_SuRE23_iPCR_3_TGACCAA_R1_001.fastq.gz
      R2: 3336_3_150122_SuRE23_iPCR_3_TGACCAA_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3336_4: 
      R1: 3336_4_150122_SuRE23_iPCR_4_ACAGTGA_R1_001.fastq.gz
      R2: 3336_4_150122_SuRE23_iPCR_4_ACAGTGA_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3336_5: 
      R1: 3336_5_150122_SuRE23_iPCR_5_GCCAATA_R1_001.fastq.gz
      R2: 3336_5_150122_SuRE23_iPCR_5_GCCAATA_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_2_L001: 
      R1: 3466_2_SuRE23_iPCR_1_CGATGTA_L001_R1_001.fastq.gz
      R2: 3466_2_SuRE23_iPCR_1_CGATGTA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_2_L002: 
      R1: 3466_2_SuRE23_iPCR_1_CGATGTA_L002_R1_001.fastq.gz
      R2: 3466_2_SuRE23_iPCR_1_CGATGTA_L002_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_3_L001: 
      R1: 3466_3_SuRE23_iPCR_2_TTAGGCA_L001_R1_001.fastq.gz
      R2: 3466_3_SuRE23_iPCR_2_TTAGGCA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_3_L002: 
      R1: 3466_3_SuRE23_iPCR_2_TTAGGCA_L002_R1_001.fastq.gz
      R2: 3466_3_SuRE23_iPCR_2_TTAGGCA_L002_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_4_L001: 
      R1: 3466_4_SuRE23_iPCR_3_TGACCAA_L001_R1_001.fastq.gz
      R2: 3466_4_SuRE23_iPCR_3_TGACCAA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_4_L002: 
      R1: 3466_4_SuRE23_iPCR_3_TGACCAA_L002_R1_001.fastq.gz
      R2: 3466_4_SuRE23_iPCR_3_TGACCAA_L002_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_5_L001: 
      R1: 3466_5_SuRE23_iPCR_4_ACAGTGA_L001_R1_001.fastq.gz
      R2: 3466_5_SuRE23_iPCR_4_ACAGTGA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_5_L002: 
      R1: 3466_5_SuRE23_iPCR_4_ACAGTGA_L002_R1_001.fastq.gz
      R2: 3466_5_SuRE23_iPCR_4_ACAGTGA_L002_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_6_L001: 
      R1: 3466_6_SuRE23_iPCR_5_GCCAATA_L001_R1_001.fastq.gz
      R2: 3466_6_SuRE23_iPCR_5_GCCAATA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_6_L002: 
      R1: 3466_6_SuRE23_iPCR_5_GCCAATA_L002_R1_001.fastq.gz
      R2: 3466_6_SuRE23_iPCR_5_GCCAATA_L002_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_HpyCH4V_phusion_1: 
      R1: 3761_1_SuRE23_HpyCH4V_phusion_1_ACTTGAA_L008_R1_001.fastq.gz
      R2: 3761_1_SuRE23_HpyCH4V_phusion_1_ACTTGAA_L008_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_TGCA
    iPCR_HpyCH4V_phusion_2: 
      R1: 3761_2_SuRE23_HpyCH4V_phusion_2_GATCAGA_L008_R1_001.fastq.gz
      R2: 3761_2_SuRE23_HpyCH4V_phusion_2_GATCAGA_L008_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_TGCA
    iPCR_HpyCH4V_kappa_1: 
      R1: 3761_3_SuRE23_HpyCH4V_kappa_1_TAGCTTA_L008_R1_001.fastq.gz
      R2: 3761_3_SuRE23_HpyCH4V_kappa_1_TAGCTTA_L008_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_TGCA
